export const ALL_POST_REQUEST="ALL_POST_REQUEST";
export const ALL_POST_SUCCESS="ALL_POST_SUCCESS";
export const ALL_POST_FAIL="ALL_POST_FAIL";

export const POST_DETAILS_REQUEST="POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS="POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL="POST_DETAILS_FAIL";

export const NEW_POST_REQUEST="NEW_POST_REQUEST";
export const NEW_POST_SUCCESS="NEW_POST_SUCCESS";
export const NEW_POST_RESET="NEW_POST_RESET";
export const NEW_POST_FAIL="NEW_POST_FAIL";



export const CURRENT_GROUP_ID="CURRENT_GROUP_ID"


export const CLEAR_ERRORS="CLEAR_ERRORS";