import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from '../components/Sidebar'
import Center from '../components/Center'
import Loader from '../components/Loader'
import axios from 'axios'
import { useState } from "react";
import {useSelector } from "react-redux";


export default function Home() {
 
  const {user,loading,isAuthenticated}=useSelector(state=>state.user)
 
  return (
    <div className="bg-green-500 h-screen overflow-hidden">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className="flex">
   {isAuthenticated==true&& <Sidebar/>}
   {isAuthenticated==true&& <Center/>}
    {/* <Sidebar/> */}
      {/* <Center/> */}
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
  return {
    props: {
      protected: true
    }
  };
}

// export const getServerSideProps=async()=>{
 
//   // const res = await axios.get("http://localhost:4000/api/v1/61f6339a79da0e82b057b898/posts")
//     // console.log(res.data)
//   return{
//       props:{
          
//           // posts:res.data
//       }
//   }
// }


